<?php

function perf_stats_init() {
  include_once(variable_get('xhgui_config_file', '/usr/share/php5-xhgui/xhprof_lib/config.php'));
  global $perf_stats_count;
  $perf_stats_count = array(
  	'node' => 0, 
  	'user' => 0, 
  	'view' => 0, 
  	'form' => 0,
  );
  
}

function perf_stats_menu() {
  $items = array();
  
  $items['admin/settings/perf_stats'] = array(
    'title' => 'Performance Statistics', 
    'page callback' => 'drupal_get_form',
    'page arguments' => array('perf_stats_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
  );
  
  return $items;
}

function perf_stats_admin_settings() {
  $form['xhgui_config_file'] = array(
    '#type' => 'textfield',
    '#title' => 'XHGui Config File Location',
    '#default_value' => variable_get('xhgui_config_file', '/usr/share/php5-xhgui/xhprof_lib/config.php'),
  );
  return system_settings_form($form);
}

function perf_stats_node_api(&$node, $op, $a3 = NULL, $a4 = NULL) {
  global $perf_stats_count;
  if ($op == 'load') {
    $perf_stats_count['node']++;
    print_r($perf_stats_count);
  }
}

function perf_stats_user_load($users) {
  global $perf_stats_count;
  $perf_stats_count['user'] += count($users);
}

function perf_stats_views_pre_execute($view) {
  global $perf_stats_count;
  $perf_stats_count['view']++;
}

function perf_stats_form_alter($form) {
  global $perf_stats_count;
  $perf_stats_count['form']++;
}

function perf_stats_exit() {
  global $devel_run_id;
  global $perf_stats_count;
  global $queries;

  $qsum = 0;
  $sqsum = 0;
  $sqcnt = 0;
  
  $tmpdir = sys_get_temp_dir();
  //@unlink($tmpdir.'/perf-stats-output');
  
  if (variable_get('dev_query', FALSE) && is_array($queries)) {
    foreach ($queries as $query) {
      $qsum += $query[1];
      if ($query[1] >= variable_get('devel_execution', 10)) {
        $sqsum += $query[1];
        $sqcnt++;
      }
    }
  }
  
  $devel_run_id = variable_get('devel_xhprof_enabled', FALSE) ? devel_shutdown_xhprof(): NULL;
  
  $data = array(
  	'xhprofid' => $devel_run_id,
    'wall_time' => 0,
    'cpu_time' => 0,
    'memory' => 0,
    'peak_memory' => 0,
  	'func_call_count' => 0,
    'node_count' => $perf_stats_count['node'],
  	'user_count' => $perf_stats_count['user'],
    'view_count' => $perf_stats_count['view'],
  	'form_count' => $perf_stats_count['form'],
  	'query_count' => count($queries),
    'query_time' => round($qsum * 1000),
  	'query_slow_time' => round($sqsum * 1000),
  	'query_slow_count' => round($sqsum * 1000),
  );
  
  file_put_contents($tmpdir.'/perf-stats-output', serialize($data));
}
